### ISSUE TITLE
[2주차] 14장 - 즉시실행함수

### ISSUE THREAD

**Issue by hwangyena** [hwangyena/js-deepdive#17]
> 📕 **책 205p**   
> 모든 코드를 즉시 실행 함수로 감싸면 모든 변수는 즉시 실행 함수의 지역 변수가 된다. .. 이 방법을 사용하면 전역 변수를 생성하지 않으므로 라이브러리 등에 자주 사용된다.

<br/>

## 질문 내용
실제 즉시 실행 함수를 사용하고 있는 라이브러리는 뭐가 있나요? 직접 그 예시를 보고 싶습니다

**Comment by Kynel** [comment]
es6 의 모듈 시스템을 사용하면 즉시 실행함수가 사실상 필요가 없어져서

최근의 라이브러리들은 아마 즉시 실행 함수를 거의 사용하지 않거나, 바벨로 컨버팅 된 파일들에서 보여질 것 같습니다.

스터디 전까지 열심히 찾아볼게요~
