### ISSUE TITLE
[2주차] 12장 함수

### ISSUE THREAD

**Issue by ohhamin** [hwangyena/js-deepdive#18]
> 📕 **책 176p**   
> 객체의 변경을 추적하려면 옵저버 패턴 등을 통해 객체를 참조를 공유하는 모든 이들에게 변경사실을 통지하고 이에 대처하는 추가 대응이 필요하다.

<br/>

**Comment by hwangyena** [comment]
wikipedia에 정의된 옵저버 패턴의 정의는 다음과 같습니다.

> **옵서버 패턴**(observer pattern)은 [객체](https://ko.wikipedia.org/wiki/%EA%B0%9D%EC%B2%B4_(%EC%BB%B4%ED%93%A8%ED%84%B0_%EA%B3%BC%ED%95%99) "객체 (컴퓨터 과학)")의 상태 변화를 관찰하는 관찰자들, 즉 옵저버들의 목록을 객체에 등록하여 상태 변화가 있을 때마다 [메서드](https://ko.wikipedia.org/wiki/%EB%A9%94%EC%84%9C%EB%93%9C "메서드") 등을 통해 객체가 직접 목록의 각 옵저버에게 통지하도록 하는 [디자인 패턴](https://ko.wikipedia.org/wiki/%EB%94%94%EC%9E%90%EC%9D%B8_%ED%8C%A8%ED%84%B4 "디자인 패턴")이다. 주로 분산 이벤트 핸들링 시스템을 구현하는 데 사용된다. [발행/구독 모델](https://ko.wikipedia.org/wiki/%EB%B0%9C%ED%96%89/%EA%B5%AC%EB%8F%85_%EB%AA%A8%EB%8D%B8 "발행/구독 모델")로 알려져 있기도 하다.
<br/>


다시 말해, 이벤트들을 **구독**(subscribe)하여, 이벤트가 발생할 때 연관된 객체에게 미리 정의해 둔 동작을 수행하게끔 하는 프로그래밍 패턴입니다.
![image](https://github.com/hwangyena/js-deepdive/assets/70925962/03c21969-f026-4ac7-a05a-fbd84ca9c1db)
1. View가 Model을 구독(subscribe)한다. => Model에게 이벤트 발생시 실행할 함수를 등록
2. 버튼에 이벤트가 발생한다.
3. Model (Observer)가 이벤트를 확인 후, 저장된 함수를 실행한다.

특징은 아래와 같습니다.
- 실시간으로 한 객체의 변경사항을 다른 객체에 전파할 수 있다.
- Observer 들은 항시 관찰 대상을 주시하는 것이 아닌, subscribe해 변화가 생기면 알림을 받는다.
- JS에서는 대표적으로 Observer 패턴과 Iterator 패턴을 결합한 라이브러리 `RxJS`가 있다.


<br/>
참고 

[wikipedia](https://ko.wikipedia.org/wiki/%EC%98%B5%EC%84%9C%EB%B2%84_%ED%8C%A8%ED%84%B4) 
[옵저버-패턴-개념-떠먹여드립니다](https://velog.io/@haero_kim/%EC%98%B5%EC%A0%80%EB%B2%84-%ED%8C%A8%ED%84%B4-%EA%B0%9C%EB%85%90-%EB%96%A0%EB%A8%B9%EC%97%AC%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4)
[옵저버 패턴이란?](https://gobae.tistory.com/121)
