### ISSUE TITLE
[4주차] 20장 - with?

### ISSUE THREAD

**Issue by hwangyena** [hwangyena/js-deepdive#28]
> 📕 **책 318p**   
> with 문을 사용하면 SyntaxError가 발생한다.

<br/>

## 질문 내용
책에 with 문에 대한 설명이 너무 부족한 것 같아, 추가 설명 부탁드립니다.
[MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/with)에서 현재는 권장하지 않던데, 그 이유도 궁금합니다!

**Comment by sunghyuki** [comment]
> Use of the `with` statement is not recommended, as it may be the source of confusing bugs and compatibility issues. See the "Ambiguity Contra" paragraph in the "Description" section below for details.
> 

자바스크립트는 규정되지 않은 이름을 포함하는 스크립트 또는 함수의 실행 컨텍스트와 연관된 범위 체인을 검색하여 규정되지 않은 이름을 검색합니다. with문은 해당 개체를 평가하는 동안 이 개체를 해당 범위 체인의 head에 추가합니다. (규정되지 않은 이름을 검색 문제)

### **[[Syntax](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/with#syntax)](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/with#syntax)**

```jsx
with (expression)
      statement
```

### Pros & Cons

`Pros` : 긴 객체 참조를 반복해서 사용해야 할 필요가 있는 경우(with에 필요한 스코프 체인 변경은 연산 비용이 들지 않음)

```jsx
var r = 10, a, x, y;
with (Math) {
    a = PI * r * r;
    x = r * cos(PI);
    y = r * sin(PI / 2);
}

// 하지만 해당 이점은 임시변수를 통해 객체에 대한 참조를 저장함으로써 해결할 수 있습니다.

const { PI, cos, sin } = Math;
a = PI * r * r;
x = r * cos(PI);
y = r * sin(PI);
```

`Cons` : 모호성

```jsx
function f(x, o) {
  with (o) {
    console.log(x);
  }
}
```

**Comment by hwangyena** [comment]
자세한 답변 감사합니다!
