### ISSUE TITLE
[4주차] 22장 - this와 bind

### ISSUE THREAD

**Issue by hwangyena** [hwangyena/js-deepdive#29]
> 📕 **책 357p**   
> bind 메서드는 this 바인딩이 교체된 함수를 새롭게 생성해 반환한다. 메서드의 this와 메서드 내부의 중첩 함수 또는 콜백 함수의 this가 불일치하는 문제를 해결할 때 유용하다.

<br/>

## 질문 내용
![image](https://github.com/hwangyena/js-deepdive/assets/70925962/678e0a73-127b-4018-b94b-6cf38005dbf7)
bind로 this가 불일치하는 문제를 해결가능하다고 했는데, 왜 위코드에서는 window를 반환하는걸까요?

```js
const obj = {
  value: 100,
  foo() {
    console.log("foo's this: ", this);  // {value: 100, foo: ƒ}
    console.log("foo's this.value: ", this.value); // 100

    // 메서드 내에서 정의한 중첩 함수
    function bar() {
      console.log("bar's this: ", this); // window

        function zoo(){
            console.log('zoo',this);
        };
        zoo.bind(this);

        zoo();
    }

    bar.bind(this);
    bar();
  }
};
```

**Comment by sunghyuki** [comment]
### 자바스크립트 엔진

## 👇

### 실행 가능한 코드 평가         → 전역 코드, 함수 코드, eval 코드 등

## 👇

### 실행 문맥

---

### 전역 실행 문맥

## 👇

### 함수 평가              ——————>  함수 실행 문맥

## 👇

### 전역 실행 문맥

## 👇

### 함수 평가              ——————>  함수 실행 문맥

## 👇

             ….
